version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: goambassador
      POSTGRES_PASSWORD: goambassador
      POSTGRES_DB: goambassador
    ports:
      - '5432:5432'
    volumes:
      - .dbdata:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379