version: '3.9'
services:
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: goambassador
      POSTGRES_PASSWORD: goambassador
      POSTGRES_DB: goambassador
    ports:
      - '5432:5432'
    volumes:
      - .dbdata:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  admin:
    build:
      context: ./
      dockerfile: ./docker/admin/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app/clients/admin
    depends_on:
      - backend

  ambassador:
    build:
      context: ./
      dockerfile: ./docker/ambassador/Dockerfile
    ports:
      - 3001:3001
    volumes:
      - .:/app/clients/ambassador
    depends_on:
      - backend

  checkout:
    build:
      context: ./
      dockerfile: ./docker/checkout/Dockerfile
    ports:
      - 3002:3002
    volumes:
      - .:/app/clients/checkout
    depends_on:
      - backend